# This document is released as CC-0. By contributing, you dedicate your work to
# the public domain by waiving all of your rights to the work worldwide under
# copyright law, including all related and neighboring rights, to the extent
# allowed by law

# fields (identical for gtfsFeeds and netexFeeds):
# countryIso (required) - ISO 3166-1 alpha-2 country code, e.g. "fr", "de", …
# license (optional) - license abbreviation, e.g. "CC0", "CC-BY 4.0", …
# attribution (required) - name of the data provider (should be used as attribution for licenses that require it, e.g. CC-BY)
# feedUrl (required) - gtfs file url
# infoUrl (required) - url that provides additional information about the feed, usually the website "feedUrl" was taken from
# comments (optional) - additional comments, e.g. regarding the coverage of a feed ("only covers ~95% of all transport")

[[gtfsFeeds]]
  countryIso = "de"
  license = "CC-BY 4.0"
  attribution = "DELFI/opendata-oepnv.de"
  feedUrl = "https://de.data.public-transport.earth/gtfs-germany.zip"
  infoUrl = "https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View"
  comments = """
  Unfortunately, this feed only covers ~75% of all public transportation (as of 4/2020), mainly because some regional providers are still not included. If this is insufficient for you, consider using the german NETEX feed, which has a higher coverage, or manually combine <a href="https://gtfs.mfdz.de/">available regional feeds</a>. Furthermore, the official feed is hidden behind a login form, so the download URL points to a community mirror, which doesn't have any official SLAs.
  """

[[gtfsFeeds]]
  countryIso = "ee"
  attribution = "Transpordiamet"
  feedUrl = "https://peatus.ee/gtfs/gtfs.zip"
  infoUrl = "https://www.mnt.ee/eng/public-transportation/public-transport-information-system"
  
[[gtfsFeeds]]
  countryIso = "fi"
  license = "CC-BY 4.0"
  attribution = "matka.fi"
  feedUrl = "http://185.134.88.185/gtfs.zip"
  infoUrl = "https://developer.matka.fi/pages/en/home.php"

[[gtfsFeeds]]
  countryIso = "ie"
  license = "CC-BY 4.0"
  attribution = "Transport for Ireland"
  feedUrl = "https://www.transportforireland.ie/transitData/google_transit_combined.zip"
  infoUrl = "https://www.transportforireland.ie/transitData/PT_Data.html"
  
 [[gtfsFeeds]]
  countryIso = "is"
  attribution = "Strætó"
  feedUrl = "http://opendata.straeto.is/data/gtfs/gtfs.zip"
  infoUrl = "https://straeto.is/um-straeto/opin-rafraen-gogn"
  comments = """
  Long-distance coach timetable information.
  """

[[gtfsFeeds]]
  countryIso = "lt"
  attribution = "visimarsrutai.lt"
  feedUrl = "https://www.visimarsrutai.lt/gtfs/gtfs_all.zip"
  infoUrl = "https://www.visimarsrutai.lt/gtfs/"

[[gtfsFeeds]]
  countryIso = "nl"
  license = "CC0"
  attribution = "Nationaal Toegangspunt ITS"
  feedUrl = "http://gtfs.openov.nl/gtfs-rt/gtfs-openov-nl.zip"
  infoUrl = "https://nt.ndw.nu/#/settings/multimodaal-reisinformatie-overview/1"

[[gtfsFeeds]]
  countryIso = "no"
  license = "NLOD"
  attribution = "Entur"
  feedUrl = "https://storage.googleapis.com/marduk-production/outbound/gtfs/rb_norway-aggregated-gtfs.zip"
  infoUrl = "https://developer.entur.org/stops-and-timetable-data"

[[netexFeeds]]
  countryIso = "de"
  license = "CC-BY 4.0"
  attribution = "DELFI/opendata-oepnv.de"
  feedUrl = "https://de.data.public-transport.earth/netex-germany.zip"
  infoUrl = "https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten&tx_vrrkit_view%5Bdataset_formats%5D%5B0%5D=ZIP&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View"
  comments = """
  The official feed is hidden behind a login form, so the download URL points to a community mirror, which doesn't have any official SLAs.
  """

[[netexFeeds]]
  countryIso = "no"
  license = "NLOD"
  attribution = "Entur"
  feedUrl = "https://storage.googleapis.com/marduk-production/outbound/netex/rb_norway-aggregated-netex.zip"
  infoUrl = "https://developer.entur.org/stops-and-timetable-data"
